### ISSUE TITLE
How to measure the features tracking performance?

### ISSUE THREAD

**Issue by Shiying99** [thomasjlew/davis_tracker#1]
Hi

This is an amazing job what you have done here. I am also working on the similar approach using C++.

I would like to know how you evaluate the performance of 2D features tracking. 

Best regards,
Li

**Comment by thomasjlew** [comment]
Hi, Thanks and sorry for the late reply!

For Matlab, I use profile viewer (https://ch.mathworks.com/help/matlab/ref/profile.html). It is very simple to use. So far in C++ I only used <time.h> and "clock()" to debug execution time, I'm sure there exists better alternatives.

Good luck with your project!
Best, Thomas
